### ISSUE TITLE
Buggy iconv in PHP-FPM images

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/docker#16]
### Description

Thanks for providing some docker images for Craft CMS development, I used these as a base and tweaked some stuff for my environment. I have found however that the PHP images are shipping a buggy version of iconv which is known issue in Docker land:

https://github.com/docker-library/php/issues/240

The solution is to add this to the PHP Dockerfile:

```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

This seems to be used elsewhere as well. There is a test case from the original issue to confirm if iconv is broke in the image:

```
php -d error_reporting=22527 -d display_errors=1 -r 'var_dump(iconv("UTF-8", "UTF-8//IGNORE", "This is the Euro symbol '\''€'\''."));'
```

If the above returns:

```Notice: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed in Command line code on line 1```

iconv is broke. Which does happen. SEOMatic triggered the issue and led me to finding the workaround for Docker.

Just wanted to flag this for anyone who might be using the images.

**Comment by jasonmccallister** [comment]
@jamesmacwhite thank you for letting us know, I will take a look and try to get a fix in soon!

**Comment by jamesmacwhite** [comment]
Thanks, I've confirmed it with PHP 7.4, I since switched to the `-dev` image, but I'm assuming it's possibly still got the same issue.

The workaround above solves it, I found several other Craft CMS docker images using the above, so I think it's possibly worth including it.

Thank for providing some nice images though, switching from nanobox to Docker was less painful with the premade images.

**Comment by jamesmacwhite** [comment]
@jasonmccallister Did you get a chance to look at this at all? I'm not sure who else is potentially hitting this but a popular plugin SEOMatic will trigger this and that's quite widely used. Granted, not everyone is using Docker either, but when I was testing Nitro 2.x, it hit this as well.

**Comment by jasonmccallister** [comment]
@jamesmacwhite we have definitely had a few conversations in Discord about this, but it appears there is not a clear fix yet. Going to test a few things based on some recommendations.

**Comment by jamesmacwhite** [comment]
@jasonmccallister Thanks, for the update. I think that's possibly a good fix. The alternative, would be something like this:

```
RUN apk add --upgrade gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so
```

**Comment by jasonmccallister** [comment]
@jamesmacwhite this was pushed to the PHP 7.3 and higher images last week. If you want to verify its working as expected I think we can close this out! Thank you for the report!

**Comment by jamesmacwhite** [comment]
I have been able to use Nitro 2 with a Craft CMS 3 site that uses SEOMatic and have not hit this, so I think it should be resolved!

**Comment by jasonmccallister** [comment]
Great, thank you! Will close this as resolved!

**Comment by michaelroper** [comment]
Thanks Jason, this also fixed my Craft 2 w/SEOmatic site that was having issues!
