### ISSUE TITLE
Set depends_on for certain containers to control starting order

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/docker#17]
### Description

I think this would be similar to #15 but the docker-compose.yml example could make use of `depends_on` for certain containers in order to make sure dependencies for those containers are present before it starts.

A couple of examples of where this might be beneficial in some cases, without handling this.

* If console starts before the DB backend is available, this will lead to a possible exit code or error in the container
* If the nginx container starts and tries to load before PHP-FPM is present, it will not recognise part of the `default.conf` and throw an exit code error in the container.

Setting `depends_on` will help prevent such edge cases. A safe fixed order would be something like:

* php-fpm (No direct dependency for itself)
* mysql/mariadb/postgres (No direct dependency for itself)
* redis (No direct dependency for itself)
* ngnix (php-fpm, should be started before it, so the `default.conf` can be loaded without issues)
* console (php-fpm and the DB backend should be available before ./craft commands are called)

**Comment by jonathanmelville** [comment]
This would be awesome. The console container immediately exits for me on startup every time as the database is never up before the console container starts.

**Comment by timkelty** [comment]
Boom! https://github.com/craftcms/docker#running-locally-with-docker-compose
