### ISSUE TITLE
MySQL 8.0: mbind: Operation not permitted logs in console

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/docker#20]
### Description

When using the MySQL 8.0 container, you can see a lot of `mbind: Operation not permitted` log spam in the console.

A fix is using `cap_add` on a `docker-compose.yml` such as:

```
service:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
```

Nitro 2.x is affected by this when using MySQL 8.

More info here: https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log

To clarify this doesn't break anything in terms of MySQL 8 usage, but will spam the console logs.

### Steps to reproduce

1. Create a docker environment using MySQL 8.
2. See the above errors logged

### Additional info

- Craft version: 3.6.7
- PHP version: 7.4
- Database driver & version: MySQL 8

**Comment by jasonmccallister** [comment]
@jamesmacwhite can you verify if this is an issue with the latest Nitro version? We are setting that capability on Nitro database containers going forward https://github.com/craftcms/nitro/blob/main/command/apply/internal/databasecontainer/databasecontainer.go#L174

**Comment by jamesmacwhite** [comment]
@jasonmccallister Sorry, never replied!

Yes I believe this is now solved when using Nitro as it's setting the SYS_NICE capability.
