### ISSUE TITLE
PHP open_basedir restrictions

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/docker#21]
### Description
When using the Nginx images, the `open_basedir` PHP setting is set on the images. The Nginx configuration we are using is explicitly setting that value here: https://github.com/craftcms/docker/blob/stable/nginx/craftcms/php_fastcgi.conf#L16. Which was generated from https://www.digitalocean.com/community/tools/nginx. 

This can create problems trying to access tools outside of the `/app` directory. Original report: https://discord.com/channels/456442477667418113/707324026577485934/813816543313657856

Need to look into why DO is explicitly setting this value.

**Comment by danbrellis** [comment]
I just came across this as it was preventing me from installing plugins through the web interface: **Error: is_dir(): open_basedir restriction in effect. File(/home/www-data/.composer/cache) is not within the allowed path(s): (/app/:/usr/lib/php/:/tmp/)**

Can you explain why it is just for dev images (I don't have access to the discord channel)? Alternatively, can you provide a way to include .composer/cache in the open_basedir paths?

Thanks.

**Comment by jasonmccallister** [comment]
@danbrellis composer tries to set a "smart" path for caches using the current username and `.composer` directory, in the image case it is `/home/www-data/.composer`. In Nitro v2, we define the `COMPOSER_HOME` environment variable to `/tmp` to avoid this issue. 

For local development, using the `dev` images has a bunch of extra settings and tools (e.g. composer, git, database tools) but the "production" images do not make any assumptions. The best approach for handling composer on production is to add a multi-stage build process [outlined here](https://github.com/craftcms/docker#usage).

This issue is closed, but has not been released yet. I'm not certain we won't remove it from the production images but I want to verify it won'y break any upstream users if that makes sense?
