### ISSUE TITLE
Error when running image transform: No JPEG support in this PHP build

### ISSUE THREAD

**Issue by mariusgiger** [craftcms/docker#25]
### Description

Error when running image transform.

In /app/vendor/craftcms/cms/src/services/Images.php(207): craft\image\Raster->loadImage('/app/storage/ru...')

Caused by:
in Imagine\Gd::createImageFromString()
imagecreatefromstring(): No JPEG support in this PHP build

### Steps to reproduce

1. Try running image transform on a JPEG image using `craftcms/nginx:8.0`

### Possible solution

Configure gd with JPEG support
docker-php-ext-configure gd --with-freetype --with-jpeg
docker-php-ext-install -j$(nproc) gd 

Is there a specific reason why this was not done?

### Additional info

- Craft version: 3.6.6
- Image version: craftcms/nginx:8.0

**Comment by khalwat** [comment]
To fix this for GD change this: https://github.com/craftcms/docker/blob/main/8.0/Dockerfile#L53

```
    docker-php-ext-configure gd && \
```

to this: https://github.com/nystudio107/docker-images/blob/master/php-prod-base/php-8.0-alpine/Dockerfile#L60

```
    docker-php-ext-configure \
        gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
```

**Comment by aloco** [comment]
Hi, 

we are using `webp` with image transforms and realized that it is not working anymore with new projects we are creating with nitro. 

```
[error][craft\errors\AssetTransformException] craft\errors\AssetTransformException: The `webp` format is not supported on this server! in /app/vendor/craftcms/cms/src/services/AssetTransforms.php:1526
```

Is it possible that your change dropped webp support? I am almost sure it was working before with your Dockerfiles. I suspect this line https://github.com/craftcms/docker/blob/main/7.4/Dockerfile#L56

@khalwat explicitly suggested `--with-webp` but it is missing in the Dockerfile (only `--with-jpeg`)

Thank you for looking into this
