### ISSUE TITLE
Don't need to expose port 9003 for Xdebug

### ISSUE THREAD

**Issue by khalwat** [craftcms/docker#30]
In the various `dev.Dockerfile`s you have:

```
# expose the xdebug port
EXPOSE 9003
```

While it's probably not harming anything, you don't need to expose port `9003` for Xdebug (version 2.x or 3.x), because it's Xdebug that reaches out and connects to client/IDE and not the other way around.

[expose](https://docs.docker.com/engine/reference/builder/#expose) is only needed if the container needs to listen on that port, which in Xdebug's case, it doesn't.

Fixed via PR: https://github.com/craftcms/docker/pull/31

**Comment by timkelty** [comment]
Fixed in the latest version of the images (`1.3.1`)!
