### ISSUE TITLE
Xdebug setting for "client_host" and "mode"

### ISSUE THREAD

**Issue by rocknrolaf** [craftcms/docker#34]
### Description

We have trouble getting xdebug connected to phpstorm (using the "craftcms/nginx:8.0-dev" container). Unless we add the "client_host" and "mode" setting:

```
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.mode=debug
```

Maybe its due to the nginx-proxy (https://hub.docker.com/r/jwilder/nginx-proxy) we use in front of the other containers.
Would it be possible to add these settings to the craft-cms-xdebug.ini file?

Thanks!

### Additional info

- Craft version: Craft Pro 3.7.4
- PHP version: 8.0.3
- Database driver & version: MySQL 5.5.5

**Comment by timkelty** [comment]
@rocknrolaf The latest version of the images (`1.3.1`) now set `xdebug.mode=develop,debug`.
We don't set `xdebug.client_host=host.docker.internal` because that is platform-specific, but you can set it via env easily: https://github.com/craftcms/docker#using-xdebug
