### ISSUE TITLE
.env file issue

### ISSUE THREAD

**Issue by mikos** [craftcms/docker#5]
Docker Compose does not expect quotes around variable values in a .env file. Instructing Docker Compose to use the .env file generated by Craft results in the quotes being interpreted literally.

**Comment by jasonmccallister** [comment]
@mikos this is something we have discussed a few times, most project .env examples do not include the `"` in the file, I'll discuss with the team and maybe we can make a change to the default that ships with https://github.com/craftcms/craft.

**Comment by brandonkelly** [comment]
The [craftcms/craft](https://github.com/craftcms/craft) starter project no longer includes quotes in its [.env.example](https://github.com/craftcms/craft/blob/master/.env.example) file, and as of the next Craft release (3.5.8), Craft will no longer include quotes in the environment variables it dynamically adds to the `.env` file, unless the value contains a space. (https://github.com/craftcms/cms/commit/ca9eb766364989f56d258809e33c1acf6cf3661e)

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that change.
