### ISSUE TITLE
Disable opcache on dev images by default

### ISSUE THREAD

**Issue by timkelty** [craftcms/docker#8]
As it is now, editing any files via host-mount isn't going to work, because opcache is enabled and validating timestamps.

This is easily overcome with something like:

```
    environment:
      PHP_OPCACHE_ENABLE: 0
```

…but I'm wondering if given that there is a -dev version, it would make sense to do it there by default?

Or maybe, if all `-dev` is going to do is enable xdebug…you could just ditch the -dev versions and handle via build args (`ENABLE_XDEBUG`).

That may not be a great idea though, as I believe it prevents those layers from being cacheable?

**Comment by jasonmccallister** [comment]
@timkelty we could add a build argument to the dev build to disable that by default. When I'm developing I typically don't run into issues with opcache being enabled, in fact I have been bitten by deploying to an environment with opcache enabled and my code not working as expected (aka needed a refresh). 

Happy to take a PR that ads the ARG and ENV for disabling opcache on dev though: https://github.com/craftcms/docker/blob/7.4/dev.Dockerfile

**Comment by timkelty** [comment]
Hmmm…I wonder why I got bitten by it so quickly?
Right away, no changes were reflected unless I did an `opcache_reset()`.

Maybe it was because I was exclusively testing my entry point `index.php`?
Not sure, but it was the first time I ran into it locally.

**Comment by mikos** [comment]
I'm fairly sure I got bitten by OPCACHE being enabled on the dev image too. Even with Craft in devMode I had to restart the app container to see changes I'd made to the twig templates.

**Comment by jasonmccallister** [comment]
I'm going to look at updating the arg to disable opcache on dev images. 

I still think it is useful to have a separate development image that is only used in a `docker-compose.yaml` file. The build steps each team takes vary so much that it would be nice to have a single image that is more flexible, but could lead to a bad configuration going into a production environment.

**Comment by timkelty** [comment]
👯‍♂️

**Comment by kylecotter** [comment]
Of course Googling and going through GH issues leads me to a @timkelty thread...

Just wanted to chime in that in testing my specific setup of Docker for Mac + Mutagen + Craft Docker images with `opcache` enabled during local dev, enabling `opcache.validate_timestamps` per @jasonmccallister's thread [here](https://github.com/craftcms/nitro/issues/129) seems to be the best of both worlds re: speed vs seeing things immediately.
